### ISSUE TITLE
sync: extend API to new flags

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobblerclient#5]
When using the `sync` API you cannot pass the newly introduced flags
```bash
      --dhcp             write DHCP config files and restart service
      --dns              write DNS config files and restart service
      --systems string   run a sync only on specified systems
```

Info: https://cobbler.readthedocs.io/en/latest/cobbler.html#cobbler-sync

**Comment by SchoolGuy** [comment]
The PR #10 has this already implemented and tested. Thus once the PR is merged this issue can be considered done.
